name: "Build Scheduler"

on:
  workflow_dispatch:
  schedule:
  - cron:  '2 1 * * 0'

jobs:
  scheduler:
    name: Build Trigger
    runs-on: ubuntu-latest
    strategy:
      matrix:
        version: [ 'legacy', 'stable', 'mainline' ]
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v1
      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}
      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          push: true
          platforms: linux/amd64,linux/arm64
          tags: openmage/nginx:${{ matrix.version }}
          context: ./src
          file: ./src/Dockerfile-${{ matrix.version }}
