name: "Build Scheduler"

on:
  workflow_dispatch:
  schedule:
  - cron:  '2 1 * * 0'

jobs:
  scheduler:
    name: Build Trigger
    runs-on: ubuntu-latest
    strategy:
      matrix:
        version: [ '1.19.10', '1.20.2', 'latest' ]
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}
      - name: Build and push
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: openmage/nginx:${{ matrix.version }}
          context: ./src
          file: ./src/Dockerfile-${{ matrix.version }}
